name: send email notifiaction on any release 

decsciption: 
  This action sends an email notification when a new release is created in the repository.
  It uses the `actions/github-script` action to send the email using the SendGrid API.
 

branding:
  icon: mail
  color: blue

inputs:
  from-email:
    required: true
  to-email:
    required: true
  subject:
    required: true
  markdown-body:
    required: true
  api-key:
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --api-key= ${{ inputs.api-key }}
    - --from= ${{ inputs.from-email }}
    - --to= ${{ inputs.to-email }}
    - --subject= ${{ inputs.subject }}
    - --markdown-body= ${{ inputs.markdown-body }}
